CREATE TABLE DATA_TABLE (
    ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL,
    Project_Name VARCHAR2(300),
    Project_Description VARCHAR2(300),
    Project_Start_Date DATE,
    Project_End_Date DATE,
    Stage_Name VARCHAR2(300),
    Stage_Start_Date DATE,
    Stage_End_Date DATE,
    Stage_Tasks_Code VARCHAR2(300),
    Stage_Tasks_Start_Date DATE,
    Stage_Tasks_End_Date DATE,
    Stage_Tasks_Name VARCHAR2(300),
    Stage_Tasks_Status VARCHAR2(300),
    Assigned_Person_Name VARCHAR2(300),
    Assigned_Person_Last_Name VARCHAR2(300),
    Assigned_Person_Position VARCHAR2(300),
    Assigned_Person_Department VARCHAR2(300),
    Team_Lead_Name VARCHAR2(300),
    Team_Lead_Last_Name VARCHAR2(300)
);

--DROP TABLE DATA_TABLE;

INSERT INTO DATA_TABLE(Project_Name,Project_Description,Project_Start_Date,Project_End_Date,Stage_Name,Stage_Start_Date,Stage_End_Date,Stage_Tasks_Code,Stage_Tasks_Start_Date,Stage_Tasks_End_Date,Stage_Tasks_Name,Stage_Tasks_Status,Assigned_Person_Name,Assigned_Person_Last_Name,Assigned_Person_Position,Assigned_Person_Department,Team_Lead_Name,Team_Lead_Last_Name) VALUES('Global Ticket','Продажа билетов по всему миру','01-01-2019','07-04-2021','Планирование','01-01-2019','01-03-2019','PLA-001','01-01-2019','15-01-2019','Проектирование планирования','Выполнена','Волчик','Владислав','Project Manager','Management','','');
INSERT INTO DATA_TABLE(Project_Name,Project_Description,Project_Start_Date,Project_End_Date,Stage_Name,Stage_Start_Date,Stage_End_Date,Stage_Tasks_Code,Stage_Tasks_Start_Date,Stage_Tasks_End_Date,Stage_Tasks_Name,Stage_Tasks_Status,Assigned_Person_Name,Assigned_Person_Last_Name,Assigned_Person_Position,Assigned_Person_Department,Team_Lead_Name,Team_Lead_Last_Name) VALUES('Global Ticket','Продажа билетов по всему миру','01-01-2019','07-04-2021','Планирование','01-02-2019','01-03-2019','PLA-002','15-01-2019','01-02-2019','Разработка планирования','Выполнена','Илья','Шапиро','Scrum Master','Management','','');
INSERT INTO DATA_TABLE(Project_Name,Project_Description,Project_Start_Date,Project_End_Date,Stage_Name,Stage_Start_Date,Stage_End_Date,Stage_Tasks_Code,Stage_Tasks_Start_Date,Stage_Tasks_End_Date,Stage_Tasks_Name,Stage_Tasks_Status,Assigned_Person_Name,Assigned_Person_Last_Name,Assigned_Person_Position,Assigned_Person_Department,Team_Lead_Name,Team_Lead_Last_Name) VALUES('Global Ticket','Продажа билетов по всему миру','01-01-2019','07-04-2021','Планирование','01-02-2019','01-03-2019','PLA-003','01-02-2019','01-03-2019','Реализация','Выполнена','Гутько','Антон','Architect','Development','','');
INSERT INTO DATA_TABLE(Project_Name,Project_Description,Project_Start_Date,Project_End_Date,Stage_Name,Stage_Start_Date,Stage_End_Date,Stage_Tasks_Code,Stage_Tasks_Start_Date,Stage_Tasks_End_Date,Stage_Tasks_Name,Stage_Tasks_Status,Assigned_Person_Name,Assigned_Person_Last_Name,Assigned_Person_Position,Assigned_Person_Department,Team_Lead_Name,Team_Lead_Last_Name) VALUES('Global Ticket','Продажа билетов по всему миру','01-01-2019','07-04-2021','Дизайн','01-02-2019','01-04-2019','DIS-001','01-02-2019','15-02-2019','Проектирование дизайна','Проектирование','Игнат','Фомин','Developer','Development','Дмитрий','Куделич');
INSERT INTO DATA_TABLE(Project_Name,Project_Description,Project_Start_Date,Project_End_Date,Stage_Name,Stage_Start_Date,Stage_End_Date,Stage_Tasks_Code,Stage_Tasks_Start_Date,Stage_Tasks_End_Date,Stage_Tasks_Name,Stage_Tasks_Status,Assigned_Person_Name,Assigned_Person_Last_Name,Assigned_Person_Position,Assigned_Person_Department,Team_Lead_Name,Team_Lead_Last_Name) VALUES('Global Ticket','Продажа билетов по всему миру','01-01-2019','07-04-2021','Дизайн','01-02-2019','01-04-2019','DIS-002','15-02-2019','15-03-2019','Разработка дизайна','Разработка','Анатолий','Агейчик','Developer','Development','Дмитрий','Куделич');
INSERT INTO DATA_TABLE(Project_Name,Project_Description,Project_Start_Date,Project_End_Date,Stage_Name,Stage_Start_Date,Stage_End_Date,Stage_Tasks_Code,Stage_Tasks_Start_Date,Stage_Tasks_End_Date,Stage_Tasks_Name,Stage_Tasks_Status,Assigned_Person_Name,Assigned_Person_Last_Name,Assigned_Person_Position,Assigned_Person_Department,Team_Lead_Name,Team_Lead_Last_Name) VALUES('Global Ticket','Продажа билетов по всему миру','01-01-2019','07-04-2021','Дизайн','01-02-2019','01-04-2019','DIS-003','15-03-2019','01-04-2019','Реализация решения','Реализация','Игнат','Фомин','Developer','Development','Дмитрий','Куделич');
INSERT INTO DATA_TABLE(Project_Name,Project_Description,Project_Start_Date,Project_End_Date,Stage_Name,Stage_Start_Date,Stage_End_Date,Stage_Tasks_Code,Stage_Tasks_Start_Date,Stage_Tasks_End_Date,Stage_Tasks_Name,Stage_Tasks_Status,Assigned_Person_Name,Assigned_Person_Last_Name,Assigned_Person_Position,Assigned_Person_Department,Team_Lead_Name,Team_Lead_Last_Name) VALUES('Global Ticket','Продажа билетов по всему миру','01-01-2019','07-04-2021','Разработка','01-03-2019','01-05-2020','DEV-001','01-03-2019','01-04-2019','Задача 1','Отменена','Дмитрий','Куделич','DEV Team Lead','Development','','');
INSERT INTO DATA_TABLE(Project_Name,Project_Description,Project_Start_Date,Project_End_Date,Stage_Name,Stage_Start_Date,Stage_End_Date,Stage_Tasks_Code,Stage_Tasks_Start_Date,Stage_Tasks_End_Date,Stage_Tasks_Name,Stage_Tasks_Status,Assigned_Person_Name,Assigned_Person_Last_Name,Assigned_Person_Position,Assigned_Person_Department,Team_Lead_Name,Team_Lead_Last_Name) VALUES('Global Ticket','Продажа билетов по всему миру','01-01-2019','07-04-2021','Разработка','01-03-2019','01-05-2020','DEV-001','01-04-2019','01-05-2019','Задача 2','Выполнена','Игнат','Фомин','Developer','Development','Дмитрий','Куделич');
INSERT INTO DATA_TABLE(Project_Name,Project_Description,Project_Start_Date,Project_End_Date,Stage_Name,Stage_Start_Date,Stage_End_Date,Stage_Tasks_Code,Stage_Tasks_Start_Date,Stage_Tasks_End_Date,Stage_Tasks_Name,Stage_Tasks_Status,Assigned_Person_Name,Assigned_Person_Last_Name,Assigned_Person_Position,Assigned_Person_Department,Team_Lead_Name,Team_Lead_Last_Name) VALUES('Global Ticket','Продажа билетов по всему миру','01-01-2019','07-04-2021','Разработка','01-03-2019','01-05-2020','DEV-002','01-05-2019','01-06-2019','Задача 3','Выполнена','Анатолий','Агейчик','Developer','Development','Дмитрий','Куделич');
INSERT INTO DATA_TABLE(Project_Name,Project_Description,Project_Start_Date,Project_End_Date,Stage_Name,Stage_Start_Date,Stage_End_Date,Stage_Tasks_Code,Stage_Tasks_Start_Date,Stage_Tasks_End_Date,Stage_Tasks_Name,Stage_Tasks_Status,Assigned_Person_Name,Assigned_Person_Last_Name,Assigned_Person_Position,Assigned_Person_Department,Team_Lead_Name,Team_Lead_Last_Name) VALUES('Global Ticket','Продажа билетов по всему миру','01-01-2019','07-04-2021','Разработка','01-03-2019','01-05-2020','DEV-003','01-06-2019','01-07-2019','Задача 4','Выполнена','Игнат','Фомин','Developer','Development','Дмитрий','Куделич');
INSERT INTO DATA_TABLE(Project_Name,Project_Description,Project_Start_Date,Project_End_Date,Stage_Name,Stage_Start_Date,Stage_End_Date,Stage_Tasks_Code,Stage_Tasks_Start_Date,Stage_Tasks_End_Date,Stage_Tasks_Name,Stage_Tasks_Status,Assigned_Person_Name,Assigned_Person_Last_Name,Assigned_Person_Position,Assigned_Person_Department,Team_Lead_Name,Team_Lead_Last_Name) VALUES('Global Ticket','Продажа билетов по всему миру','01-01-2019','07-04-2021','Разработка','01-03-2019','01-05-2020','DEV-004','01-07-2019','01-08-2019','Задача 5','Выполняется','Анатолий','Агейчик','Developer','Development','Дмитрий','Куделич');
INSERT INTO DATA_TABLE(Project_Name,Project_Description,Project_Start_Date,Project_End_Date,Stage_Name,Stage_Start_Date,Stage_End_Date,Stage_Tasks_Code,Stage_Tasks_Start_Date,Stage_Tasks_End_Date,Stage_Tasks_Name,Stage_Tasks_Status,Assigned_Person_Name,Assigned_Person_Last_Name,Assigned_Person_Position,Assigned_Person_Department,Team_Lead_Name,Team_Lead_Last_Name) VALUES('Global Ticket','Продажа билетов по всему миру','01-01-2019','07-04-2021','Разработка','01-03-2019','01-05-2020','DEV-005','01-08-2019','01-09-2019','Задача 6','Выполняется','Денис','Мартиневский','DEV Team Lead','Development','','');
INSERT INTO DATA_TABLE(Project_Name,Project_Description,Project_Start_Date,Project_End_Date,Stage_Name,Stage_Start_Date,Stage_End_Date,Stage_Tasks_Code,Stage_Tasks_Start_Date,Stage_Tasks_End_Date,Stage_Tasks_Name,Stage_Tasks_Status,Assigned_Person_Name,Assigned_Person_Last_Name,Assigned_Person_Position,Assigned_Person_Department,Team_Lead_Name,Team_Lead_Last_Name) VALUES('Global Ticket','Продажа билетов по всему миру','01-01-2019','07-04-2021','Разработка','01-03-2019','01-05-2020','DEV-006','01-09-2019','01-10-2019','Задача 7','Выполняется','Алексей','Тухолко','Developer','Development','Денис','Мартиневский');
INSERT INTO DATA_TABLE(Project_Name,Project_Description,Project_Start_Date,Project_End_Date,Stage_Name,Stage_Start_Date,Stage_End_Date,Stage_Tasks_Code,Stage_Tasks_Start_Date,Stage_Tasks_End_Date,Stage_Tasks_Name,Stage_Tasks_Status,Assigned_Person_Name,Assigned_Person_Last_Name,Assigned_Person_Position,Assigned_Person_Department,Team_Lead_Name,Team_Lead_Last_Name) VALUES('Global Ticket','Продажа билетов по всему миру','01-01-2019','07-04-2021','Разработка','01-03-2019','01-05-2020','DEV-007','01-10-2019','01-11-2019','Задача 8','Готова к тестированию','Роман','Жилко','Developer','Development','Денис','Мартиневский');
INSERT INTO DATA_TABLE(Project_Name,Project_Description,Project_Start_Date,Project_End_Date,Stage_Name,Stage_Start_Date,Stage_End_Date,Stage_Tasks_Code,Stage_Tasks_Start_Date,Stage_Tasks_End_Date,Stage_Tasks_Name,Stage_Tasks_Status,Assigned_Person_Name,Assigned_Person_Last_Name,Assigned_Person_Position,Assigned_Person_Department,Team_Lead_Name,Team_Lead_Last_Name) VALUES('Global Ticket','Продажа билетов по всему миру','01-01-2019','07-04-2021','Разработка','01-03-2019','01-05-2020','DEV-008','01-11-2019','01-12-2019','Задача 9','Заморожена','Алексей','Тухолко','Developer','Development','Денис','Мартиневский');
INSERT INTO DATA_TABLE(Project_Name,Project_Description,Project_Start_Date,Project_End_Date,Stage_Name,Stage_Start_Date,Stage_End_Date,Stage_Tasks_Code,Stage_Tasks_Start_Date,Stage_Tasks_End_Date,Stage_Tasks_Name,Stage_Tasks_Status,Assigned_Person_Name,Assigned_Person_Last_Name,Assigned_Person_Position,Assigned_Person_Department,Team_Lead_Name,Team_Lead_Last_Name) VALUES('Global Ticket','Продажа билетов по всему миру','01-01-2019','07-04-2021','Разработка','01-03-2019','01-05-2020','DEV-009','01-12-2019','01-05-2020','Задача 10','Готова к выполнению','Роман','Жилко','Developer','Development','Денис','Мартиневский');
INSERT INTO DATA_TABLE(Project_Name,Project_Description,Project_Start_Date,Project_End_Date,Stage_Name,Stage_Start_Date,Stage_End_Date,Stage_Tasks_Code,Stage_Tasks_Start_Date,Stage_Tasks_End_Date,Stage_Tasks_Name,Stage_Tasks_Status,Assigned_Person_Name,Assigned_Person_Last_Name,Assigned_Person_Position,Assigned_Person_Department,Team_Lead_Name,Team_Lead_Last_Name) VALUES('Global Ticket','Продажа билетов по всему миру','01-01-2019','07-04-2021','Тестирование','01-03-2019','01-05-2020','TST-001','01-03-2019','20-03-2019','Тестирование задачи 1','Тестируется','Константин','Збойчик','QA Team Lead','Testing','','');
INSERT INTO DATA_TABLE(Project_Name,Project_Description,Project_Start_Date,Project_End_Date,Stage_Name,Stage_Start_Date,Stage_End_Date,Stage_Tasks_Code,Stage_Tasks_Start_Date,Stage_Tasks_End_Date,Stage_Tasks_Name,Stage_Tasks_Status,Assigned_Person_Name,Assigned_Person_Last_Name,Assigned_Person_Position,Assigned_Person_Department,Team_Lead_Name,Team_Lead_Last_Name) VALUES('Global Ticket','Продажа билетов по всему миру','01-01-2019','07-04-2021','Тестирование','01-03-2019','01-05-2020','TST-002','20-03-2019','20-04-2019','Тестирование задачи 2','Выполняется','Фаррухшох','Бобоев','Tester','Testing','Константин','Збойчик');
INSERT INTO DATA_TABLE(Project_Name,Project_Description,Project_Start_Date,Project_End_Date,Stage_Name,Stage_Start_Date,Stage_End_Date,Stage_Tasks_Code,Stage_Tasks_Start_Date,Stage_Tasks_End_Date,Stage_Tasks_Name,Stage_Tasks_Status,Assigned_Person_Name,Assigned_Person_Last_Name,Assigned_Person_Position,Assigned_Person_Department,Team_Lead_Name,Team_Lead_Last_Name) VALUES('Global Ticket','Продажа билетов по всему миру','01-01-2019','07-04-2021','Тестирование','01-03-2019','01-05-2020','TST-003','20-04-2019','01-05-2020','Тестирование задачи 3','Выполнена','Фаррухшох','Бобоев','Tester','Testing','Константин','Збойчик');
INSERT INTO DATA_TABLE(Project_Name,Project_Description,Project_Start_Date,Project_End_Date,Stage_Name,Stage_Start_Date,Stage_End_Date,Stage_Tasks_Code,Stage_Tasks_Start_Date,Stage_Tasks_End_Date,Stage_Tasks_Name,Stage_Tasks_Status,Assigned_Person_Name,Assigned_Person_Last_Name,Assigned_Person_Position,Assigned_Person_Department,Team_Lead_Name,Team_Lead_Last_Name) VALUES('Global Ticket','Продажа билетов по всему миру','01-01-2019','07-04-2021','Поддержка','01-08-2019','01-01-2023','SUP-001','01-08-2019','01-09-2019','Проектирование подддержки','Проектирование','Гапанович','Евгений','SUP Team Lead','Support Department','','');
INSERT INTO DATA_TABLE(Project_Name,Project_Description,Project_Start_Date,Project_End_Date,Stage_Name,Stage_Start_Date,Stage_End_Date,Stage_Tasks_Code,Stage_Tasks_Start_Date,Stage_Tasks_End_Date,Stage_Tasks_Name,Stage_Tasks_Status,Assigned_Person_Name,Assigned_Person_Last_Name,Assigned_Person_Position,Assigned_Person_Department,Team_Lead_Name,Team_Lead_Last_Name) VALUES('Global Ticket','Продажа билетов по всему миру','01-01-2019','07-04-2021','Поддержка','01-08-2019','01-01-2023','SUP-002','01-09-2019','01-01-2023','Поддержка','Готова к выполнению','Марченко','Иван','Support Engineer','Support Department','Гапанович','Евгений');
INSERT INTO DATA_TABLE(Project_Name,Project_Description,Project_Start_Date,Project_End_Date,Stage_Name,Stage_Start_Date,Stage_End_Date,Stage_Tasks_Code,Stage_Tasks_Start_Date,Stage_Tasks_End_Date,Stage_Tasks_Name,Stage_Tasks_Status,Assigned_Person_Name,Assigned_Person_Last_Name,Assigned_Person_Position,Assigned_Person_Department,Team_Lead_Name,Team_Lead_Last_Name) VALUES('Global Ticket','Продажа билетов по всему миру','01-01-2019','07-04-2021','Поддержка','01-08-2019','01-01-2023','SUP-003','01-08-2019','01-09-2019','Формирование команды','Выполнена','Ильин','Александр','Support Engineer','Support Department','Гапанович','Евгений');