CREATE TABLE DEPARTMENT (
    ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    HEAD_ID NUMBER NOT NULL,
    CONSTRAINT PK_DEPARTMENT PRIMARY KEY (ID) ENABLE
)
TABLESPACE MMF_9_3_DATA;

-- COMMENT ON COLUMN DEPARTMENT.ID IS 'Unique value, serves as the primary key for the table';
-- COMMENT ON COLUMN DEPARTMENT.LABEL IS 'Internal label of a department';