CREATE TABLE STAGE (
    ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL
);

COMMENT ON COLUMN STAGE.ID IS 'Unique value, serves as the primary key';
COMMENT ON COLUMN STAGE.PROJECT_ID IS 'Determines a project that this stage belongs to';
COMMENT ON COLUMN STAGE.START_DATE IS 'Date when stage starts';
COMMENT ON COLUMN STAGE.FINISH_DATE IS 'Date when stage ends';