CREATE TABLE EMPLOYEE (
    ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL,
    TEAM_ID NUMBER,
    HEAD_ID NUMBER,
    FIRSTNAME NVARCHAR2(100) NOT NULL,
    MIDDLENAME NVARCHAR2(100),
    LASTNAME NVARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(350) NOT NULL,
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (ID) ENABLE
)
TABLESPACE MMF_9_3_DATA;