CREATE TABLE EMPLOYEE_SKILL (
    ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL,
    EMPLOYEE_ID NUMBER NOT NULL,
    SKILL_ID NUMBER NOT NULL,
    CONSTRAINT PK_EMPLOYEE_SKILL PRIMARY KEY (ID) ENABLE
)
TABLESPACE MMF_9_3_DATA;