CREATE TABLE ROLE (
    ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL,
    LABEL VARCHAR2(100) NOT NULL
);

COMMENT ON COLUMN ROLE.ID IS 'Unique value, serves as the primary key';
COMMENT ON COLUMN ROLE.LABEL IS 'Role name';