CREATE TABLE ROLE (
    ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL,
    LABEL VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_ROLE PRIMARY KEY (ID) ENABLE
)
TABLESPACE MMF_9_3_DATA;

-- COMMENT ON COLUMN ROLE.ID IS 'Unique value, serves as the primary key';
-- COMMENT ON COLUMN ROLE.LABEL IS 'The name of a role, constrained with the set of value';