
ALTER TABLE DEPARTMENT ADD CONSTRAINT FK_DEPARTMENT_EMPLOYEE FOREIGN KEY(HEAD_ID)
REFERENCES EMPLOYEE (ID);

ALTER TABLE TEAM ADD CONSTRAINT FK_TEAM_DEPARTMENT FOREIGN KEY(DEPARTMENT_ID) 
REFERENCES DEPARTMENT(ID);

ALTER TABLE TEAM ADD CONSTRAINT FK_TEAM_EMPLOYEE FOREIGN KEY(LEAD_ID)
REFERENCES EMPLOYEE(ID);

ALTER TABLE TEAM ADD CONSTRAINT FK_TEAM_PROJECT FOREIGN KEY(PROJECT_ID)
REFERENCES PROJECT(ID);

ALTER TABLE PROJECT ADD CONSTRAINT FK_PROJECT_MANAGER FOREIGN KEY(MANAGER_ID)
REFERENCES EMPLOYEE(ID);

ALTER TABLE PROJECT_STAGE ADD CONSTRAINT FK_PROJECT_STAGE_PROJECT FOREIGN KEY(PROJECT_ID)
REFERENCES PROJECT(ID);

ALTER TABLE PROJECT_STAGE ADD CONSTRAINT FK_PROJECT_STAGE_STAGE FOREIGN KEY(STAGE_ID)
REFERENCES STAGE(ID);

ALTER TABLE TASK ADD CONSTRAINT FK_TASK_STAGE FOREIGN KEY(STAGE_ID)
REFERENCES STAGE(ID);

ALTER TABLE TASK ADD CONSTRAINT FK_TASK_EMPLOYEE FOREIGN KEY(EMPLOYEE_ID)
REFERENCES EMPLOYEE(ID);

ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_EMPLOYEE_TEAM FOREIGN KEY(TEAM_ID)
REFERENCES TEAM(ID);

ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_EMPLOYEE_HEAD FOREIGN KEY(HEAD_ID)
REFERENCES EMPLOYEE(ID);

ALTER TABLE EMPLOYEE_SKILL ADD CONSTRAINT FK_EMPLOYEE_SKILL_EMPLOYEE FOREIGN KEY(EMPLOYEE_ID)
REFERENCES EMPLOYEE(ID);

ALTER TABLE EMPLOYEE_SKILL ADD CONSTRAINT FK_EMPLOYEE_SKILL_SKILL FOREIGN KEY(SKILL_ID)
REFERENCES SKILL(ID);

ALTER TABLE EMPLOYEE_ROLE ADD CONSTRAINT FK_EMPLOYEE_ROLE_EMPLOYEE FOREIGN KEY(EMPLOYEE_ID)
REFERENCES EMPLOYEE(ID);

ALTER TABLE EMPLOYEE_ROLE ADD CONSTRAINT FK_EMPLOYEE_ROLE_ROLE FOREIGN KEY(ROLE_ID)
REFERENCES ROLE(ID);