DEFINE USER_NAME = &&1
DEFINE DATA_TABLESPACE = '&&USER_NAME._DATA'
DEFINE INDEX_TABLESPACE = '&&USER_NAME._IDX'

-- Primary Keys

ALTER TABLE DEPARTMENT ADD CONSTRAINT PK_DEPARTMENT PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;
ALTER TABLE DEPARTMENT MOVE TABLESPACE &&DATA_TABLESPACE;

ALTER TABLE EMPLOYEE_ROLE ADD CONSTRAINT PK_EMPLOYEE_ROLE PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;
ALTER TABLE EMPLOYEE_ROLE MOVE TABLESPACE &&DATA_TABLESPACE;

ALTER TABLE EMPLOYEE_SKILL ADD CONSTRAINT PK_EMPLOYEE_SKILL PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;
ALTER TABLE EMPLOYEE_SKILL MOVE TABLESPACE &&DATA_TABLESPACE;

ALTER TABLE EMPLOYEE ADD CONSTRAINT PK_EMPLOYEE PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;
ALTER TABLE EMPLOYEE MOVE TABLESPACE &&DATA_TABLESPACE;

ALTER TABLE PROJECT ADD CONSTRAINT PK_PROJECT PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;
ALTER TABLE PROJECT MOVE TABLESPACE &&DATA_TABLESPACE;

ALTER TABLE ROLE ADD CONSTRAINT PK_ROLE PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;
ALTER TABLE ROLE MOVE TABLESPACE &&DATA_TABLESPACE;

ALTER TABLE SKILL ADD CONSTRAINT PK_SKILL PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;
ALTER TABLE SKILL MOVE TABLESPACE &&DATA_TABLESPACE;

ALTER TABLE STAGE ADD CONSTRAINT PK_STAGE PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;
ALTER TABLE STAGE MOVE TABLESPACE &&DATA_TABLESPACE;

ALTER TABLE TASK ADD CONSTRAINT PK_TASK PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;
ALTER TABLE TASK MOVE TABLESPACE &&DATA_TABLESPACE;

ALTER TABLE TEAM ADD CONSTRAINT PK_TEAM PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;
ALTER TABLE TEAM MOVE TABLESPACE &&DATA_TABLESPACE;

-- Foreign Keys

ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_EMPLOYEE_DEPARTMENT FOREIGN KEY(DEPARTMENT_ID)
REFERENCES DEPARTMENT(ID) ON DELETE SET NULL;

CREATE INDEX FK_EMPLOYEE_DEPARTMENT_I ON EMPLOYEE(DEPARTMENT_ID) TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_EMPLOYEE_TEAM FOREIGN KEY(TEAM_ID)
REFERENCES TEAM(ID) ON DELETE SET NULL;

CREATE INDEX FK_EMPLOYEE_TEAM_I ON EMPLOYEE(TEAM_ID) TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE EMPLOYEE_SKILL ADD CONSTRAINT FK_EMPLOYEE_SKILL_EMPLOYEE FOREIGN KEY(EMPLOYEE_ID)
REFERENCES EMPLOYEE(ID) ON DELETE CASCADE;

CREATE INDEX FK_EMPLOYEE_SKILL_EMPLOYEE_I ON EMPLOYEE_SKILL(EMPLOYEE_ID) TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE EMPLOYEE_SKILL ADD CONSTRAINT FK_EMPLOYEE_SKILL_SKILL FOREIGN KEY(SKILL_ID)
REFERENCES SKILL(ID) ON DELETE CASCADE;

CREATE INDEX FK_EMPLOYEE_SKILL_SKILL_I ON EMPLOYEE_SKILL(SKILL_ID) TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE EMPLOYEE_ROLE ADD CONSTRAINT FK_EMPLOYEE_ROLE_EMPLOYEE FOREIGN KEY(EMPLOYEE_ID)
REFERENCES EMPLOYEE(ID) ON DELETE CASCADE;

CREATE INDEX FK_EMPLOYEE_ROLE_EMPLOYEE_I ON EMPLOYEE_ROLE(EMPLOYEE_ID) TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE EMPLOYEE_ROLE ADD CONSTRAINT FK_EMPLOYEE_ROLE_ROLE FOREIGN KEY(ROLE_ID)
REFERENCES ROLE(ID) ON DELETE CASCADE;

CREATE INDEX FK_EMPLOYEE_ROLE_ROLE_I ON EMPLOYEE_ROLE(ROLE_ID) TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE TEAM ADD CONSTRAINT FK_TEAM_LEAD FOREIGN KEY(LEAD_ID)
REFERENCES EMPLOYEE(ID) ON DELETE SET NULL;

CREATE INDEX FK_TEAM_LEAD_I ON TEAM(LEAD_ID) TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE TEAM ADD CONSTRAINT FK_TEAM_PROJECT FOREIGN KEY(PROJECT_ID)
REFERENCES PROJECT(ID) ON DELETE SET NULL;

CREATE INDEX FK_TEAM_PROJECT_I ON TEAM(PROJECT_ID) TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE PROJECT ADD CONSTRAINT FK_PROJECT_MANAGER FOREIGN KEY(MANAGER_ID)
REFERENCES EMPLOYEE(ID) ON DELETE SET NULL;

CREATE INDEX FK_PROJECT_MANAGER_I ON PROJECT(MANAGER_ID) TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE STAGE ADD CONSTRAINT FK_STAGE_PROJECT FOREIGN KEY(PROJECT_ID)
REFERENCES PROJECT(ID) ON DELETE CASCADE;

CREATE INDEX FK_STAGE_PROJECT_I ON STAGE(PROJECT_ID) TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE TASK ADD CONSTRAINT FK_TASK_PROJECT FOREIGN KEY(PROJECT_ID)
REFERENCES PROJECT(ID) ON DELETE CASCADE;

CREATE INDEX FK_TASK_PROJECT_I ON TASK(PROJECT_ID) TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE TASK ADD CONSTRAINT FK_TASK_STAGE FOREIGN KEY(STAGE_ID)
REFERENCES STAGE(ID) ON DELETE CASCADE;

CREATE INDEX FK_TASK_STAGE_I ON TASK(STAGE_ID) TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE TASK ADD CONSTRAINT FK_TASK_EMPLOYEE FOREIGN KEY(ASSIGNEE_ID)
REFERENCES EMPLOYEE(ID) ON DELETE SET NULL;

CREATE INDEX FK_TASK_EMPLOYEE_I ON TASK(ASSIGNEE_ID) TABLESPACE &&INDEX_TABLESPACE;


UNDEFINE USER_NAME
UNDEFINE DATA_TABLESPACE
UNDEFINE INDEX_TABLESPACE


