CREATE TABLE PERSONS_ROLES (
    ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL
,   PERSON_ID NUMBER NOT NULL
,   ROLE_ID NUMBER NOT NULL
,   CONSTRAINT PK_PERSONS_ROLES PRIMARY KEY
    (
        ID
    )
    ENABLE
)
TABLESPACE MMF_9_3_DATA;

COMMENT ON COLUMN PERSONS_ROLES.ID IS 'Unique value, serves as the primary key';
COMMENT ON COLUMN PERSONS_ROLES.PERSON_ID IS 'Determines employee';
COMMENT ON COLUMN PERSONS_ROLES.ROLE_ID IS 'Determines a role of an employee';