ALTER TABLE PERSON ADD CONSTRAINT fk_PERSON_TEAM_ID FOREIGN KEY(ID)
REFERENCES TEAM (ID);

ALTER TABLE PERSONS_ROLES ADD CONSTRAINT fk_PERSONS_ROLES_PERSON_ID FOREIGN KEY(ID)
REFERENCES PERSON (ID);

ALTER TABLE PERSONS_ROLES ADD CONSTRAINT fk_PERSONS_ROLES_ROLE_ID FOREIGN KEY(ID)
REFERENCES ROLE (ID);

ALTER TABLE SKILL ADD CONSTRAINT fk_SKILL_DEVELOPER_ID FOREIGN KEY(ID)
REFERENCES PERSON (ID);

ALTER TABLE TEAM ADD CONSTRAINT fk_TEAM_DEPARTMENT_ID FOREIGN KEY(ID)
REFERENCES DEPARTMENT (ID);

ALTER TABLE TEAM ADD CONSTRAINT fk_TEAM_PROJECT_ID FOREIGN KEY(ID)
REFERENCES PROJECT (ID);

ALTER TABLE STAGE ADD CONSTRAINT fk_STAGE_PROJECT_ID FOREIGN KEY(ID)
REFERENCES PROJECT (ID);

ALTER TABLE TASK ADD CONSTRAINT fk_TASK_STAGE_ID FOREIGN KEY(ID)
REFERENCES STAGE (ID);

ALTER TABLE TASK ADD CONSTRAINT fk_TASK_DEVELOPER_ID FOREIGN KEY(ID)
REFERENCES PERSON (ID);
