CREATE TABLE PROJECT_STAGE (
    ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL,
    PROJECT_ID NUMBER NOT NULL,
    STAGE_ID NUMBER NOT NULL,
    CONSTRAINT PK_PROJECT_STAGE PRIMARY KEY (ID) ENABLE
)
TABLESPACE MMF_9_3_DATA;