CREATE TABLE PERSON (
    ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL
,   FIRSTNAME VARCHAR2(30) NOT NULL
,   PATRONYMIC VARCHAR2(30) 
,   SURNAME VARCHAR2(30) NOT NULL
,   EMAIL VARCHAR2(20) NOT NULL
,   TEAM_ID NUMBER NULL
,   CONSTRAINT PK_PERSON PRIMARY KEY 
    (
        ID
    ) 
    ENABLE
)
TABLESPACE MMF_9_3_DATA;

COMMENT ON COLUMN PERSON.ID IS 'Unique value, serves as the primary key';
COMMENT ON COLUMN PERSON.FIRSTNAME IS 'Name of a person';
COMMENT ON COLUMN PERSON.PATRONYMIC IS 'Patronymic of a person';
COMMENT ON COLUMN PERSON.SURNAME IS 'Surname of a person';
COMMENT ON COLUMN PERSON.EMAIL IS 'Email of a person';
COMMENT ON COLUMN PERSON.TEAM_ID IS 'Determines a team that an employee belongs to';