CREATE TABLE SKILL (
    ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL
,   PERSON_ID NUMBER NOT NULL
,   LABEL VARCHAR2(20) NOT NULL
,   CONSTRAINT PK_SKILL PRIMARY KEY
    (
        ID
    )
    ENABLE
)
TABLESPACE MMF_9_3_DATA;

COMMENT ON COLUMN SKILL.ID IS 'Unique value, serves as the primary key';
COMMENT ON COLUMN SKILL.PERSON_ID IS 'Determines an employee that owns a skill';
COMMENT ON COLUMN SKILL.LABEL IS 'Name of a skill';