DEFINE USER_NAME = &&1
DEFINE DATA_TABLESPACE = '&&USER_NAME._DATA'
DEFINE INDEX_TABLESPACE = '&&USER_NAME._IDX'

-- Primary Keys

ALTER TABLE DEPARTMENT ADD CONSTRAINT PK_DEPARTMENT PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;
ALTER TABLE DEPARTMENT MOVE TABLESPACE &&DATA_TABLESPACE;

ALTER TABLE EMPLOYEE_ROLE ADD CONSTRAINT PK_EMPLOYEE_ROLE PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;
ALTER TABLE EMPLOYEE_ROLE MOVE TABLESPACE &&DATA_TABLESPACE;

ALTER TABLE EMPLOYEE_SKILL ADD CONSTRAINT PK_EMPLOYEE_SKILL PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;
ALTER TABLE EMPLOYEE_SKILL MOVE TABLESPACE &&DATA_TABLESPACE;

ALTER TABLE EMPLOYEE ADD CONSTRAINT PK_EMPLOYEE PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;
ALTER TABLE EMPLOYEE MOVE TABLESPACE &&DATA_TABLESPACE;

ALTER TABLE PROJECT ADD CONSTRAINT PK_PROJECT PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;
ALTER TABLE PROJECT MOVE TABLESPACE &&DATA_TABLESPACE;

ALTER TABLE ROLE ADD CONSTRAINT PK_ROLE PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;
ALTER TABLE ROLE MOVE TABLESPACE &&DATA_TABLESPACE;

ALTER TABLE SKILL ADD CONSTRAINT PK_SKILL PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;
ALTER TABLE SKILL MOVE TABLESPACE &&DATA_TABLESPACE;

ALTER TABLE STAGE ADD CONSTRAINT PK_STAGE PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;
ALTER TABLE STAGE MOVE TABLESPACE &&DATA_TABLESPACE;

ALTER TABLE TASK ADD CONSTRAINT PK_TASK PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;
ALTER TABLE TASK MOVE TABLESPACE &&DATA_TABLESPACE;

ALTER TABLE TEAM ADD CONSTRAINT PK_TEAM PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;
ALTER TABLE TEAM MOVE TABLESPACE &&DATA_TABLESPACE;

-- Foreign Keys

ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_EMPLOYEE_DEPARTMENT FOREIGN KEY(DEPARTMENT_ID)
REFERENCES TABLE DEPARTMENT(ID) ON DELETE SET NULL USING INDEX TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_EMPLOYEE_TEAM FOREIGN KEY(TEAM_ID)
REFERENCES TABLE TEAM(ID) ON DELETE SET NULL USING INDEX TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE EMPLOYEE_SKILL ADD CONSTRAINT FK_EMPLOYEE_SKILL_EMPLOYEE FOREIGN KEY(EMPLOYEE_ID)
REFERENCES TABLE EMPLOYEE(ID) ON DELETE CASCADE USING INDEX TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE EMPLOYEE_SKILL ADD CONSTRAINT FK_EMPLOYEE_SKILL_SKILL FOREIGN KEY(SKILL_ID)
REFERENCES TABLE SKILL(ID) ON DELETE CASCADE USING INDEX TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE EMPLOYEE_ROLE ADD CONSTRAINT FK_EMPLOYEE_ROLE_EMPLOYEE FOREIGN KEY(EMPLOYEE_ID)
REFERENCES TABLE EMPLOYEE(ID) ON DELETE CASCADE USING INDEX TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE EMPLOYEE_ROLE ADD CONSTRAINT FK_EMPLOYEE_ROLE_ROLE FOREIGN KEY(ROLE_ID)
REFERENCES TABLE ROLE(ID) ON DELETE CASCADE USING INDEX TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE TEAM ADD CONSTRAINT FK_TEAM_LEAD FOREIGN KEY(LEAD_ID)
REFERENCES TABLE EMPLOYEE(ID) ON DELETE SET NULL USING INDEX TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE TEAM ADD CONSTRAINT FK_TEAM_PROJECT FOREIGN KEY(PROJECT_ID)
REFERENCES TABLE PROJECT(ID) ON DELETE SET NULL USING INDEX TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE PROJECT ADD CONSTRAINT FK_PROJECT_MANAGER FOREIGN KEY(MANAGER_ID)
REFERENCES TABLE EMPLOYEE(ID) ON DELETE SET NULL USING INDEX TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE STAGE ADD CONSTRAINT FK_STAGE_PROJECT FOREIGN KEY(PROJECT_ID)
REFERENCES TABLE PROJECT(ID) ON DELETE CASCADE USING INDEX TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE TASK ADD CONSTRAINT FK_TASK_PROJECT FOREIGN KEY(PROJECT_ID)
REFERENCES TABLE PROJECT(ID) ON DELETE CASCADE USING INDEX TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE TASK ADD CONSTRAINT FK_TASK_STAGE FOREIGN KEY(STAGE_ID)
REFERENCES TABLE STAGE(ID) ON DELETE CASCADE USING INDEX TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE TASK ADD CONSTRAINT FK_TASK_EMPLOYEE FOREIGN KEY(ASSIGNEE)
REFERENCES TABLE EMPLOYEE(ID) ON DELETE SET NULL USING INDEX TABLESPACE &&INDEX_TABLESPACE;


UNDEFINE USER_NAME
UNDEFINE DATA_TABLESPACE
UNDEFINE INDEX_TABLESPACE


