CREATE TABLE SKILL (
    ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL,
    NAME VARCHAR2(100) NOT NULL
);

COMMENT ON COLUMN SKILL.ID IS 'Unique value, serves as the primary key';
COMMENT ON COLUMN SKILL.NAME IS 'Skill name';