CREATE TABLE TEAM (
    ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL
,   DEPARTMENT_ID NUMBER NOT NULL
,   PROJECT_ID NUMBER NULL
,   CONSTRAINT PK_TEAM PRIMARY KEY 
    (
        ID
    )
    ENABLE
)
TABLESPACE MMF_9_3_DATA;

COMMENT ON COLUMN TEAM.ID IS 'Unique value, serves as the primary key';
COMMENT ON COLUMN TEAM.DEPARTMENT_ID IS 'Determines a department that a team belongs to';
COMMENT ON COLUMN TEAM.PROJECT_ID IS 'Determines a project that a team performs';